### ISSUE TITLE
I want to bridge an existing token on bsc to ethereum

### ISSUE THREAD

**Issue by zakimzf** [Sam44323/BSC-ETH-Bridge#1]
I already have an existing bsc token i want to bridge it to ethereum how do I implement this..i dont want to create a new token ..just bridge an existing token.

**Comment by Sam44323** [comment]
You can do that @zakimzf. You just need to control the supply of the tokens. Ig, you are aware of the facts of wrapped tokens, you can apply this very similar concept. In my case, I used different tokens because I wanted to test the following
- Release and Lock
- Cross token transaction

Hope it helps 😁!

**Comment by zakimzf** [comment]
It just went over my head. Can you atleast refer a repo that I could study and figure out.Or if you have already done this please link your work.
Thanks.

**Comment by Sam44323** [comment]
In a nutshell, what you can do is you can deploy the same token contract to both BSC and ETH and you can do it very easily cause both are EVM compatible. Now, If you want the total supply to be 1mil, then you can have 500K for BSC and 500K for ETH and then you can do the bridging respectively @zakimzf . You can follow this code snippet for pancake swap for reference if you want

https://github.com/pancakeswap/pancake-swap-core/blob/master/contracts/PancakePair.sol
