### ISSUE TITLE
Starting the App and Switching Tokens

### ISSUE THREAD

**Issue by CryptoDevving** [Sam44323/BSC-ETH-Bridge#4]
Do I go into each folder and use yarn start for the front end and back end? If I want to use the app?

If I have tokens already on BSC and Eth how do I connect them to this app? Where would I put the contract addresses or get the backend to bridge them?

**Comment by Sam44323** [comment]
Each folders have been managed by its own node_modules so yes you have to go to each folder and run yarn first to install the modules.

Coming to the tokens, I'm using a custom token BTK and ETK for bridging so I have the mint authority. If you want to have the testnet tokens for bridging, another extra thing you have to do is create a faucet-like service so that you have the authority to mint the native test tokens on the test networks

Hope it helps!

**Comment by CryptoDevving** [comment]
So I cannot bridge something like USDC or BUSD on this?

**Comment by Sam44323** [comment]
Not if you don't add that custom service
